### PR TITLE
Improving Travis CI

### PR DESCRIPTION
**Pull request by dpshelio**
- [x] cleanup
- [x] set up multiple runs with different dependencies
- [x] build documentation into GH pages for merged PRs
- [x] build/run benchmarks

### CODE REVIEW

**Comment by jonc125** [comment]
Looking at https://github.com/astro-informatics/sopt/blob/development/cpp/CMakeLists.txt#L23, perhaps `tools_for_tests` isn't being built?

Also, I'd expect it to be an include with `""` rather than `<>` in cpp/tests/forward_backward.cc if it's just in the build dir, not installed, so that could be another thing to try.

**Comment by jonc125** [comment]
Heh, and now it looks like the copy_tiff build is missing a library on Linux :(

**Comment by dpshelio** [comment]
It's green!!!! it's green!!! First Travis run that's green!

Now I'll add other stuff to the matrix (openmp, mpi, etc...)

**Comment by UCLGuichard** [comment]
😎 Great job!!!!

On 8 Jun 2018 6:08 pm, David Pérez-Suárez <notifications@github.com> wrote:

It's green!!!! it's green!!! First Travis run that's green!

Now I'll add other stuff to the matrix (openmp, mpi, etc...)

**Comment by UCLGuichard** [comment]
Hey @dpshelio is this ready to be reviewed ?

**Comment by dpshelio** [comment]
@UCLGuichard this is ready for review!! :)

**Pull request merged**
