### PR TITLE
chore(code-quality): remove else block(s) after return statement(s)

### PR DESCRIPTION
**Pull request by krishnakumarg1984**

### CODE REVIEW

**Review by tkoskela — COMMENTED** [review]
I personally find the logic easier to follow with if - else structure. Is there a good reason for changing it?

**Comment by mmcleod89** [comment]
I would agree that in these code samples, removing the `else` makes the code harder to read and more likely to be miscontrued. This, in my opinion, is doubly true where there are no curly braces with the `if` statement to catch the eye! 

I would generally only use this style if it's a straightforward check for a special case (like "if thing empty") at the beginning of a function followed by a large piece of (possibly nested) code that is usually executed, in which case it can make things a bit clearer by not giving undue weight to the early check.

**Comment by krishnakumarg1984** [comment]
@mmcleod89 and @tkoskela This is what the LLVM coding standards suggests

https://llvm.org/docs/CodingStandards.html#don-t-use-else-after-a-return 

> #### [Don’t use else after a return](https://llvm.org/docs/CodingStandards.html#id40)
> 
> Please do not use 'else' or 'else if' after something that interrupts control flow — like return, break, continue, goto, etc. For example:
> ```cpp
> case 'J': {
>   if (Signed) {
>     Type = Context.getsigjmp_bufType();
>     if (Type.isNull()) {
>       Error = ASTContext::GE_Missing_sigjmp_buf;
>       return QualType();
>     } else {
>       break; // Unnecessary.
>     }
>   } else {
>     Type = Context.getjmp_bufType();
>     if (Type.isNull()) {
>       Error = ASTContext::GE_Missing_jmp_buf;
>       return QualType();
>     } else {
>       break; // Unnecessary.
>     }
>   }
> }
> ```
> It is better to write it like this:
> ```cpp
> case 'J':
>   if (Signed) {
>     Type = Context.getsigjmp_bufType();
>     if (Type.isNull()) {
>       Error = ASTContext::GE_Missing_sigjmp_buf;
>       return QualType();
>     }
>   } else {
>     Type = Context.getjmp_bufType();
>     if (Type.isNull()) {
>       Error = ASTContext::GE_Missing_jmp_buf;
>       return QualType();
>     }
>   }
>   break;
> ```
> Or better yet (in this case) as:
> ```cpp
> case 'J':
>   if (Signed)
>     Type = Context.getsigjmp_bufType();
>   else
>     Type = Context.getjmp_bufType();
> 
>   if (Type.isNull()) {
>     Error = Signed ? ASTContext::GE_Missing_sigjmp_buf :
>                      ASTContext::GE_Missing_jmp_buf;
>     return QualType();
>   }
>   break;
> ```
> The idea is to **reduce indentation** and the **amount of code you have to keep track of** when reading the code.

**Comment by mmcleod89** [comment]
I agree that there is a point to the example given by llvm, but that example is not really comparable because it eliminates redundant statements for example. If I'm honest, it looks a little bit contrived, I don't think many people would write break statements this way. 

The point is I think to look at the readability of the actual changes being made to our code. 
I personally think having two `return` statements next to each other, differentiated only by indentation and with no curly braces, is much harder to read and more likely to cause confusion:
`if (fista_mixing())
      return operator()(out, gamma, x, FistaMixing());
    return operator()(out, gamma, x, NoMixing());`
 
In my opinion, in this case it's much easier to see what's happening if we use `if` and `else`.

**Comment by krishnakumarg1984** [comment]
OK. Agreed. Happy to close this one without merging.

**Pull request closed without merging**
