### PR TITLE
Add conan package

### LINKED ISSUE #271: Use cmake_find_package_generator to tidy up the Makefile
We could try [cmake_find_package_generator](https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_find_package_generator.html)

_Originally posted by @tkoskela in https://github.com/astro-informatics/sopt/pull/265#discussion_r840579973_

### LINKED ISSUE #272: Problems with libtiff provided by conan
If we remove `find_package(TIFF)` in `dependencies.cmake` and use `libtiff` installed by conan instead we get build errors. It seems that `libtiff` installed natively on all the systems we run on so this is not a breaking issue, for example the Github Actions runners find 

```
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.1.0")  
```

while our conanfile requests
```python
  self.requires("libtiff/4.0.9")
```

# Error on MacOS Monterey 12.2.1

Both libtiff versions `4.0.9` and `4.3.0` built from source with both `gcc-11`
```bash
Undefined symbols for architecture x86_64:
  "__ZN4sopt9utilities10write_tiffERKN5Eigen5ArrayIdLin1ELin1ELi0ELin1ELin1EEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE", referenced from:
      _main in copy_tiff.cc.o
  "__ZN4sopt9utilities9read_tiffERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE", referenced from:
      _main in copy_tiff.cc.o
      __ZN4sopt12notinstalled18read_standard_tiffERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE in libtools_for_tests.a(tiffwrappers.cc.o)
```

# Ubuntu

@SJaffa can you add the Ubuntu error in a comment?

### LINKED ISSUE #279: Create conan package
https://docs.conan.io/en/latest/creating_packages.html

### PR DESCRIPTION
**Pull request by tkoskela**
Closes #279 builds sopt as a package. This can be done in the build directory by e.g. `conan create .. username/channel`. I'm not entirely sure whether we should use the [username/channel](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#user-channel) naming scheme. They can also be left out. I suppose we could use something like `arc/development`

Closes #272  Libtiff works after fixing the [link line in cpp/sopt/CMakeLists.txt](https://github.com/astro-informatics/sopt/blob/8760ef1a9b5e64b0c43663715337ad128eb59653/cpp/sopt/CMakeLists.txt#L40) as described in the comments to https://github.com/conan-io/conan/issues/6639

Closes #271 I changed the generator to [CMakeDeps](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html). Although it is marked as experimental, the docs recommend using it for future compatibility. The documentation is a bit sparse but following the documentation for [cmake_find_package](https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_find_package_generator.html) helped. CMakeDeps creates separate config files for each dependency which can then be included with `find_package` in `CMakeLists.txt`. I added the `find_package()` calls back to dependencies.cmake to follow the original structure. I also added [CMakeToolchain](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html) because it makes passing variables to CMake a lot easier.

On my Mac eigen installs as `eigen-config.cmake` but on GA runners it installs as `Eigen3Config.cmake`. I'm using the same version of conan on both. This is causing errors when I call `find_package()` 🤯. The work-around suggested by @SJaffa to check for both names works for now.

### CODE REVIEW

**Comment by SJaffa** [comment]
> TODO: On my Mac eigen installs as eigen-config.cmake but on GA runners it installs as Eigen3-config.cmake. I'm using the same version of conan on both. This is causing errors when I call find_package() exploding_head.

Would it be too horrible to do
```
find_package(eigen)
if(NOT eigen_FOUND)
  find_package(Eigen3)
  # make this set eigen_FOUND if successful, or use eigen3_FOUND?
  if(NOT eigen_FOUND)
    message(FATAL_ERROR "Eigen is required")
  endif()
endif()
```
as a workaround?

**Comment by tkoskela** [comment]
I think this can finally be merged to make some progress with the build system. The package builds without a `test_package` directory which is quoted as optional in the [packaging documentation](https://docs.conan.io/en/latest/creating_packages/getting_started.html). It is used for testing the package creation works, which would not be a bad thing. I think it's just a case of creating a minimal example that calls some functions from `sopt` and builds with a minimal cmake file. Probably not more than a day or two of work but I propose leaving it for a separate PR to get this merged.

**Comment by tkoskela** [comment]
For some reason `Eigen3_INCLUDE_DIR` does not get defined on the runners, hence everything fails.

**Comment by SJaffa** [comment]
Had to update Conan to >=1.47 to get [conan.tools.files.symlinks](https://docs.conan.io/en/1.47/reference/conanfile/tools/files/symlinks.html) but once I did that this installed and built fine of my system, found eigen AND Eigen3.

So @tkoskela if you want to get the good stuff from this PR merged in I can approve it and we will deal with the eigen problem on the runners after?

**Comment by tkoskela** [comment]
It looks like there was a problem in `conan 1.51.2` that has been resolved in `1.51.3`. The Ubuntu builds have 1.51.3 and pass, but homebrew does not have it yet, and the mac builds still fail. EDIT: The third item in https://docs.conan.io/en/latest/changelog.html#aug-2022 looks like our fix. I'm fairly confident this will get resolved once hombrew gets the updated version.

In fact the stable version of https://formulae.brew.sh/formula/conan is already `1.51.3` :thinking:

**Comment by tkoskela** [comment]
After running `brew update` in the MacOS workflow, all tests now pass

**Review by SJaffa — APPROVED** [review]

**Pull request merged**
