### PR TITLE
Add Fedora image

### PR DESCRIPTION
**Pull request by 20DM**
It would be good to test on Fedora as well.
Wasn't sure how to hook this up with the fancy matrix because of the image, but that might be overkill anyway?
This is using the documentation step to test Fedora at the same time.

### CODE REVIEW

**Review by tkoskela — COMMENTED** [review]
I don't quite understand what you've done. Is it running a fedora container on an ubuntu runner to build the documentation?

**Comment by 20DM** [comment]
> I don't quite understand what you've done. Is it running a fedora container on an ubuntu runner to build the documentation?

Yes!

**Comment by tkoskela** [comment]
Why do we want to do that? :zany_face:

**Comment by 20DM** [comment]
> Why do we want to do that? 🤪

Because every time we had an in person meeting and the Fedora people tried to build the code all hell would break loose and we really should've been testing for this in the CI?

**Comment by tkoskela** [comment]
That's a fair point. But in this PR as far as I can understand you've swapped Ubuntu for Fedora. Shouldn't we rather add it to the matrix of os's we run the CI on so that we test on both?

Oh, I see why you used a container. GitHub actions doesn't offer Fedora in [standard runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for--private-repositories).

**Comment by 20DM** [comment]
> That's a fair point. But in this PR as far as I can understand you've swapped Ubuntu for Fedora. Shouldn't we rather add it to the matrix of os's we run the CI on so that we test on both?

See my note in the description: I wasn't sure how to do that elegantly given that Fedora uses an image, but the other two OS don't...? 

> Oh, I see why you used a container. GitHub actions doesn't offer Fedora in [standard runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for--private-repositories).

Yes, unfortunately it doesn't. Although DPS mentioned that he's got a Fedora machine somewhere - unclear to me how much faff it would be to get this hooked up, though.

**Comment by 20DM** [comment]
Winning! 🏆

**Review by tkoskela — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
